// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Human-readable rendering of an agent graph's IO signature, embedded in
 * [`AgentTypeSummary`].
 *
 * Each axis holds rendered type-name strings in parameter terms —
 * `Res<T>` / `ResMut<T>` for resources, `Out<T>` for outputs — produced by
 * [`GraphSignature::to_rendered`](polaris_graph::GraphSignature::to_rendered).
 *
 * **Advisory and display-only.** Type-name strings do not unify across
 * separately compiled binaries and `std::any::type_name` makes no format
 * guarantee, so never parse or compare these strings; capability checks
 * belong to the server-side contract registry, surfaced through
 * [`AgentTypeSummary::contracts`].
 */
export type AgentSignature = { 
/**
 * Non-global resources the agent's graph reads from its context
 * (`Res<T>` / `ResMut<T>` entries).
 */
requires: Array<string>, 
/**
 * Free outputs the graph reads but does not produce (`Out<T>` entries).
 */
requires_outputs: Array<string>, 
/**
 * Outputs the graph produces (`Out<T>` entries).
 */
produces: Array<string>, };
