// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of a registered agent type, returned by
 * `GET /v1/sessions/agent-types`.
 */
export type AgentTypeSummary = { 
/**
 * The agent's stable type name.
 */
name: string, };
