// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSignature } from "./AgentSignature";

/**
 * Summary of a registered agent type, returned by the agent-type listing
 * routes.
 *
 * The public `GET /v1/sessions/agent-types` route populates only
 * [`name`](Self::name). The `signature` and `contracts` fields contain
 * private graph-interface metadata and are only populated by the
 * authenticated `GET /v1/sessions/agent-types/details` route. They are also
 * additive: servers predating them omit both, and `#[serde(default)]` lets a
 * newer client deserialize such a response (`signature: None`, empty
 * `contracts`).
 */
export type AgentTypeSummary = { 
/**
 * The agent's stable type name.
 */
name: string, 
/**
 * Human-readable rendering of the agent graph's IO signature.
 *
 * `None` only when deserializing a response from a server that predates
 * signature advertisement.
 */
signature?: AgentSignature, 
/**
 * Names of the registered capability contracts this agent satisfies,
 * sorted (e.g. `["self-learn"]`).
 */
contracts?: Array<string>, };
