// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies an agent type by its stable, user-defined name.
 *
 * Wraps the `&'static str` returned by [`Agent::name`].
 *
 * # Examples
 *
 * ```
 * use polaris_sessions::AgentTypeId;
 *
 * let id = AgentTypeId::from_name("ReActAgent");
 * assert_eq!(id.as_str(), "ReActAgent");
 * ```
 */
export type AgentTypeId = string;
