// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fixed bucket granularity for the uptime endpoint's `?bucket=` query.
 *
 * The wire form uses the short string codes (`1m`, `5m`, `15m`, `1h`)
 * rather than the variant names; unknown values are rejected at
 * deserialization time so misclients cannot ask for arbitrary buckets.
 */
export type BucketGranularity = "1m" | "5m" | "15m" | "1h";
