// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTypeSummary } from "./AgentTypeSummary";

/**
 * Response body for the agent-type listing routes.
 */
export type ListAgentTypesResponse = { 
/**
 * All registered agent types.
 */
items: Array<AgentTypeSummary>, };
