// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnSummary } from "./TurnSummary";

/**
 * Response body for `GET /v1/sessions/{id}/turns`.
 */
export type ListTurnsResponse = { 
/**
 * Recorded turns for the session, oldest first.
 */
items: Array<TurnSummary>, };
