// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NavItem } from "./NavItem";
import type { Panel } from "./Panel";
import type { Section } from "./Section";

/**
 * Frozen snapshot of the registry produced by
 * [`DashboardRegistry::freeze`].
 *
 * Serialized as the body of `GET /v1/dashboard/manifest` and broadcast via
 * [`RegistryEvent::Ready`].
 *
 * `#[non_exhaustive]` so future top-level fields (e.g. `version`) can be
 * added without breaking downstream consumers that pattern-match the
 * struct.
 */
export type Manifest = { 
/**
 * Top-level navigation entries.
 */
nav_items: Array<NavItem>, 
/**
 * Sections grouping panels under nav items.
 */
sections: Array<Section>, 
/**
 * Panels — the renderable units.
 */
panels: Array<Panel>, };
