// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A top-level navigation entry contributed by a plugin.
 *
 * Frontends use [`NavItem::label`] for the link text and the entry's
 * [`Section`]s and [`Panel`]s to render its body.
 *
 * `#[non_exhaustive]` so future fields can be added without breaking
 * downstream contributors. Construct via [`NavItem::new`] +
 * [`with_metadata`](Self::with_metadata).
 */
export type NavItem = { 
/**
 * Stable identifier referenced by [`Section::nav_item_id`] and used
 * for build-time suppression via
 * [`DashboardRegistry::remove_nav_item`].
 */
id: string, 
/**
 * Human-readable label rendered in the navigation.
 */
label: string, 
/**
 * Plugin-defined extension. Free-form to allow new shapes without a
 * core crate bump.
 */
metadata?: unknown, };
