// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Transport } from "./Transport";

/**
 * A single dashboard panel: a renderable view of plugin-owned data.
 *
 * `kind` is a free-form string from the seed vocabulary documented in the
 * [crate root](crate) or a plugin-defined extension. `metadata` carries
 * kind-specific parameters and is duck-typed in v0.1.
 *
 * `#[non_exhaustive]` so future fields can be added without breaking
 * downstream contributors. Construct via [`Panel::new`] +
 * [`with_section`](Self::with_section) / [`with_metadata`](Self::with_metadata).
 */
export type Panel = { 
/**
 * Stable identifier used for build-time suppression via
 * [`DashboardRegistry::remove_panel`].
 */
id: string, 
/**
 * Optional [`Section::id`] this panel belongs to.
 */
section_id?: string | null, 
/**
 * Human-readable title rendered above the panel.
 */
title: string, 
/**
 * Rendering hint (`list`, `detail`, `timeseries`, …). See the
 * [crate-level seed vocabulary](crate).
 */
kind: string, 
/**
 * Path or URL the consumer should hit to fetch panel data.
 */
endpoint: string, 
/**
 * Wire transport for [`Self::endpoint`].
 */
transport: Transport, 
/**
 * Plugin-defined extension carrying kind-specific parameters.
 */
metadata?: unknown, };
