// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary view of one observed run, returned by
 * [`SpanBuffer::distinct_runs`].
 */
export type RunSummary = { 
/**
 * Run identifier.
 */
run_id: string, 
/**
 * Agent name, when one was attached to the run via a `RunLabels`
 * `agent_type` entry (sessions plugin convention).
 */
agent_name?: string | null, 
/**
 * ISO-8601 timestamp of the earliest span start observed for the run.
 */
started_at?: string | null, 
/**
 * Wall-clock duration of the root `polaris.graph.execute` span, when
 * observed.
 */
duration_ms?: number | null, 
/**
 * `"success"` / `"error"` / `None` — inferred from the root span's
 * level at close.
 */
outcome?: string | null, 
/**
 * Sum of `gen_ai.usage.input_tokens` across every record observed for
 * this run. `0` when the run made no token-reporting LLM calls.
 */
input_tokens: number, 
/**
 * Sum of `gen_ai.usage.output_tokens` across every record observed for
 * this run. `0` when the run made no token-reporting LLM calls.
 */
output_tokens: number, 
/**
 * Sum of `gen_ai.usage.cost_usd` across every record observed for
 * this run. `0.0` when no record carried a priced LLM call — providers
 * without a pricing entry never record the field, so this stays zero.
 */
cost_usd: number, 
/**
 * Correlation labels merged from every record observed for this run.
 *
 * Populated from the `polaris.label.<key>` tracing field convention.
 * Conventional keys include `session_id`, `agent_type`, and `turn`,
 * allowing the dashboard to join a run back to the owning session.
 */
labels?: Record<string, string>, };
