// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A logical grouping of [`Panel`]s within a [`NavItem`].
 *
 * A `NavItem` with no `Section`s renders its panels directly; with one or
 * more `Section`s, panels are grouped under section titles.
 *
 * `#[non_exhaustive]` so future fields can be added without breaking
 * downstream contributors. Construct via [`Section::new`] +
 * [`with_metadata`](Self::with_metadata).
 */
export type Section = { 
/**
 * Stable identifier referenced by [`Panel::section_id`] and used for
 * build-time suppression via [`DashboardRegistry::remove_section`].
 */
id: string, 
/**
 * [`NavItem::id`] this section belongs to.
 */
nav_item_id: string, 
/**
 * Human-readable title rendered above the section's panels.
 */
title: string, 
/**
 * Plugin-defined extension.
 */
metadata?: unknown, };
