// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A logical grouping of [`Panel`]s within a [`NavItem`].
 *
 * Every panel is expected to belong to a section: [`Panel::section_id`]
 * is the only formal linkage from a panel back to its [`NavItem`] (via
 * `section.nav_item_id`), so consumers that render panels grouped by
 * section will drop section-less panels. A nav item with no logical
 * grouping should still register a single "Overview" section so its
 * panels render.
 *
 * `#[non_exhaustive]` so future fields can be added without breaking
 * downstream contributors. Construct via [`Section::new`] +
 * [`with_metadata`](Self::with_metadata).
 */
export type Section = { 
/**
 * Stable identifier referenced by [`Panel::section_id`] and used for
 * build-time suppression via [`DashboardRegistry::remove_section`].
 */
id: string, 
/**
 * [`NavItem::id`] this section belongs to.
 */
nav_item_id: string, 
/**
 * Human-readable title rendered above the section's panels.
 */
title: string, 
/**
 * Plugin-defined extension.
 */
metadata?: unknown, };
