// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTypeId } from "./AgentTypeId";
import type { SessionId } from "./SessionId";
import type { SessionStatus } from "./SessionStatus";

/**
 * Metadata about a session returned by
 * [`SessionsAPI::session_info`](crate::api::SessionsAPI::session_info).
 */
export type SessionMetadata = { 
/**
 * The session's unique identifier.
 */
session_id: SessionId, 
/**
 * The type of the agent that owns this session.
 */
agent_type: AgentTypeId, 
/**
 * The current turn number.
 */
turn_number: number, 
/**
 * ISO 8601 UTC timestamp of when the session was created.
 */
created_at: string, 
/**
 * The session's current status.
 */
status: SessionStatus, };
