// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary view of one observed session, returned by
 * [`SpanBuffer::distinct_sessions`].
 *
 * Pairs with the [`RunSummary`] / [`SpanTree`] surfaces — clicking a
 * session in the dashboard's tracing-sessions list populates
 * `session_id` for the existing `sessions-runs` / `sessions-run-tree`
 * chain.
 */
export type SessionSummary = { 
/**
 * Session identifier (the `session_id` correlation label).
 */
session_id: string, 
/**
 * Agent name, when one was attached via the `agent_type` label.
 */
agent_name?: string | null, 
/**
 * Number of distinct runs observed for the session.
 */
run_count: number, 
/**
 * ISO-8601 timestamp of the earliest span start observed for the
 * session.
 */
started_at?: string | null, 
/**
 * ISO-8601 timestamp of the most recent record observed for the
 * session.
 */
last_seen_at?: string | null, };
