// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unique identifier for a session.
 *
 * Generated via [`nanoid`] by default, or created from an existing string.
 * Display format is `session_{id}`.
 *
 * # Examples
 *
 * ```
 * use polaris_sessions::SessionId;
 *
 * // Generate a random ID.
 * let id = SessionId::new();
 *
 * // Create from a known string (useful for testing or deterministic IDs).
 * let id = SessionId::from_string("my-session-1");
 * assert_eq!(id.as_str(), "my-session-1");
 * assert_eq!(format!("{id}"), "session_my-session-1");
 * ```
 */
export type SessionId = string;
