// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UptimeStatus } from "./UptimeStatus";

/**
 * A single bucket in an uptime time-series.
 */
export type SessionUptimeBucket = { 
/**
 * ISO 8601 UTC start of the bucket window (inclusive).
 */
start: string, 
/**
 * ISO 8601 UTC end of the bucket window (exclusive).
 */
end: string, 
/**
 * Dominant status during the bucket window.
 */
status: UptimeStatus, };
