// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BucketGranularity } from "./BucketGranularity";
import type { SessionUptimeBucket } from "./SessionUptimeBucket";

/**
 * Response body for `GET /v1/sessions/{id}/uptime`.
 */
export type SessionUptimeResponse = { 
/**
 * The bucket granularity that was used.
 */
bucket: BucketGranularity, 
/**
 * ISO 8601 UTC start of the queried range (inclusive).
 */
since: string, 
/**
 * ISO 8601 UTC end of the queried range (exclusive).
 */
until: string, 
/**
 * Buckets in chronological order; length is
 * `(until − since) / bucket`.
 */
buckets: Array<SessionUptimeBucket>, };
