// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One event payload nested inside a [`SpanNode`].
 */
export type SpanEvent = { 
/**
 * ISO-8601 timestamp the event fired.
 */
ts: string, 
/**
 * Event level.
 */
level: string, 
/**
 * Tracing metadata target.
 */
target: string, 
/**
 * Event name (typically derived from the source location).
 */
name: string, 
/**
 * Optional message field extracted from the tracing payload.
 */
message?: string | null, 
/**
 * Structured fields captured from the event.
 */
fields: Record<string, unknown>, };
