// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpanEvent } from "./SpanEvent";

/**
 * One node in a [`SpanTree`].
 */
export type SpanNode = { 
/**
 * Stable per-process span id.
 */
span_id: string, 
/**
 * Parent span id when nested.
 */
parent_span_id?: string | null, 
/**
 * Span name (matches the `name!` argument from the macro).
 */
name: string, 
/**
 * Span level (`info`, `warn`, ...).
 */
level: string, 
/**
 * Tracing metadata target.
 */
target: string, 
/**
 * ISO-8601 timestamp the span opened.
 */
started_at?: string | null, 
/**
 * ISO-8601 timestamp the span closed.
 */
closed_at?: string | null, 
/**
 * Wall-clock duration in milliseconds.
 */
duration_ms?: number | null, 
/**
 * Structured fields captured on the span.
 */
fields: Record<string, unknown>, 
/**
 * Inline event records that fired inside this span. Empty when the
 * tree was built with `include_payloads = false`.
 */
events?: Array<SpanEvent>, 
/**
 * Child span nodes.
 */
children?: Array<SpanNode>, };
