// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpanNode } from "./SpanNode";

/**
 * Hierarchical view of one run, returned by [`SpanBuffer::run_tree`].
 */
export type SpanTree = { 
/**
 * Run identifier this tree describes.
 */
run_id: string, 
/**
 * Agent name, when one was attached via run labels.
 */
agent_name?: string | null, 
/**
 * Earliest span start observed for the run.
 */
started_at?: string | null, 
/**
 * Root span duration in milliseconds.
 */
duration_ms?: number | null, 
/**
 * Inferred outcome of the run.
 */
outcome?: string | null, 
/**
 * Correlation labels merged from every record observed for this run.
 * Mirrors [`RunSummary::labels`].
 */
labels?: Record<string, string>, 
/**
 * Top-level span nodes (no parent in the buffer).
 */
roots: Array<SpanNode>, 
/**
 * Spans whose declared parent is missing from the buffer (e.g., the
 * parent aged out of the ring).
 */
orphans?: Array<SpanNode>, };
