// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire kind for tracing records emitted by
 * [`RecordingLayer`](super::RecordingLayer).
 */
export type SpanKind = "event" | "span-close";
