// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpanKind } from "./SpanKind";

/**
 * Wire representation of a recent tracing record.
 */
export type SpanRecord = { 
/**
 * ISO-8601 UTC timestamp the record was emitted (span close time or
 * event time).
 */
ts: string, 
/**
 * ISO-8601 UTC timestamp the span started. `None` for `Event`
 * records (events have no separate start) and for spans that did not
 * pass through the dashboard layer's open path.
 */
started_at?: string | null, 
/**
 * Closed-span duration in milliseconds. `None` for `Event` records or
 * spans missing a recorded open.
 */
duration_ms?: number | null, 
/**
 * Lower-cased tracing level (`info`, `warn`, `error`, ...).
 */
level: string, 
/**
 * Tracing metadata target.
 */
target: string, 
/**
 * Event name or the associated span name.
 */
name: string, 
/**
 * Record kind.
 */
kind: SpanKind, 
/**
 * Stable per-process span identifier. `None` for `Event` records that
 * fired outside any span.
 */
span_id?: string | null, 
/**
 * Parent span identifier when the record is nested under another span.
 */
parent_span_id?: string | null, 
/**
 * Run identifier (`run_id` from `polaris_graph` hooks), propagated to
 * every span and event that fires under a graph execution. `None`
 * outside graph execution.
 */
run_id?: string | null, 
/**
 * Correlation labels captured for this record.
 *
 * Populated from any tracing field whose name starts with the
 * `polaris.label.` prefix — the suffix becomes the label key and the
 * stringified value becomes the label value. Labels are inherited
 * down the parent span chain, so a label set on a session turn span
 * surfaces on every nested graph span and event.
 *
 * Conventional keys include `session_id`, `agent_type`, and `turn`.
 */
labels?: Record<string, string>, 
/**
 * Structured fields captured from the event or span.
 */
fields: Record<string, unknown>, 
/**
 * Optional message field extracted from the tracing payload.
 */
message?: string | null, };
