// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsageBreakdown } from "./TokenUsageBreakdown";
import type { TokenUsageTotals } from "./TokenUsageTotals";

/**
 * Wire response for the `/v1/.../usage` endpoint family.
 */
export type TokenUsageResponse = { 
/**
 * Aggregate totals across every record that contributed.
 */
totals: TokenUsageTotals, 
/**
 * Per-model breakdown, keyed by `gen_ai.request.model`. Sorted by
 * descending `total_tokens`, then by key for stability.
 */
by_model: Array<TokenUsageBreakdown>, 
/**
 * Per-provider breakdown, keyed by `gen_ai.provider.name`. Same sort.
 */
by_provider: Array<TokenUsageBreakdown>, 
/**
 * Per-`agent_type` breakdown, keyed by the `agent_type` correlation
 * label. Same sort.
 */
by_agent_type: Array<TokenUsageBreakdown>, 
/**
 * Number of span records that contributed at least one token. Useful
 * when distinguishing "no LLM calls happened" from "buffer is empty".
 */
source_span_count: number, };
