// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-bucket token totals (and optional computed cost).
 */
export type TokenUsageTotals = { 
/**
 * Sum of full-price (uncached) input tokens reported by the aggregated
 * spans.
 */
input_tokens: number, 
/**
 * Sum of output tokens reported by the aggregated spans.
 */
output_tokens: number, 
/**
 * Sum of input tokens served from the prompt cache (billed at the
 * cache-read rate). Zero for providers/calls without prompt caching.
 */
cache_read_tokens: number, 
/**
 * Sum of input tokens written to the prompt cache (billed at the
 * cache-write rate). Zero for providers/calls without prompt caching.
 */
cache_creation_tokens: number, 
/**
 * `input_tokens + output_tokens + cache_read_tokens + cache_creation_tokens`.
 * Pre-computed for convenience; matches each call's `Usage::total_tokens`.
 */
total_tokens: number, 
/**
 * Computed cost in USD when a [`UsagePricing`] table covered at least
 * one of the aggregated `(provider, model)` pairs. `None` when no
 * pricing was registered or no rate matched a contributing bucket.
 */
cost_usd?: number | null, };
