// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsageTotals } from "./TokenUsageTotals";

/**
 * One row in a breakdown — totals attributed to a single key value.
 */
export type TokenUsageBreakdown = { 
/**
 * Breakdown key — the model, provider, or `agent_type` the row totals
 * belong to. The literal string `"unknown"` is used when the source
 * span lacked the corresponding attribute.
 */
key: string, 
/**
 * Totals attributed to this key.
 */
usage: TokenUsageTotals, };
