// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-bucket token totals (and optional computed cost).
 */
export type TokenUsageTotals = { 
/**
 * Sum of input tokens reported by the aggregated spans.
 */
input_tokens: number, 
/**
 * Sum of output tokens reported by the aggregated spans.
 */
output_tokens: number, 
/**
 * `input_tokens + output_tokens`. Pre-computed for convenience.
 */
total_tokens: number, 
/**
 * Computed cost in USD when a [`UsagePricing`] table covered at least
 * one of the aggregated `(provider, model)` pairs. `None` when no
 * pricing was registered or no rate matched a contributing bucket.
 */
cost_usd?: number | null, };
