// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire transport for a [`Panel`]'s data feed.
 *
 * `#[non_exhaustive]` so additional transports (e.g. gRPC) can be added
 * without breaking downstream `match` arms.
 */
export type Transport = "rest" | "sse" | "web-socket";
