// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnStatus } from "./TurnStatus";

/**
 * Summary entry for `GET /v1/sessions/{id}/turns`.
 *
 * When the request includes `?include=messages`, the retained
 * [`IOMessage`] array is embedded in [`messages`](Self::messages).
 * Otherwise that field is omitted from the JSON payload. The
 * [`messages_truncated`](Self::messages_truncated) flag indicates whether
 * recording limits omitted any data.
 */
export type TurnSummary = { 
/**
 * The turn number.
 */
turn: number, 
/**
 * ISO 8601 UTC timestamp when the turn began.
 */
started_at: string, 
/**
 * ISO 8601 UTC timestamp when the turn finished (None if still running).
 */
finished_at: string | null, 
/**
 * Outcome of the turn.
 */
status: TurnStatus, 
/**
 * Number of IO messages emitted during the turn.
 */
io_message_count: number, 
/**
 * Whether one or more messages or payload bytes were omitted from
 * retained turn history because a recording limit was reached.
 */
messages_truncated: boolean, 
/**
 * Truncated text of the most recent IO message, if any.
 */
last_message_preview: string | null, 
/**
 * Retained IO messages, only present when the request was made with
 * `?include=messages`.
 */
messages?: unknown[], };
