// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of a single turn within a session's history.
 */
export type TurnStatus = "running" | "completed" | "failed";
