// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnStatus } from "./TurnStatus";

/**
 * Full turn payload returned by `GET /v1/sessions/{id}/turns/{n}`.
 */
export type Turn = { 
/**
 * The turn number.
 */
turn: number, 
/**
 * ISO 8601 UTC timestamp when the turn began.
 */
started_at: string, 
/**
 * ISO 8601 UTC timestamp when the turn finished (None if still running).
 */
finished_at: string | null, 
/**
 * Outcome of the turn.
 */
status: TurnStatus, 
/**
 * IO messages emitted during the turn, in arrival order.
 */
messages: unknown[], };
