// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle status reported for a single uptime bucket.
 */
export type UptimeStatus = "unknown" | "idle" | "active" | "terminated";
